### ISSUE TITLE
Screencast-Keys can't be enabeled "module 'screencast_keys.utils' has no attribute 'addon_updater'"

### ISSUE THREAD

**Issue by IndigoWizard** [nutti/Screencast-Keys#124]
**System Information**
  
* OS: Windows 10
* Blender version: 2.93.7
* Add-on version: 3.6 and 3.7

**Expected behavior**  
To install / enable the add-on without issue.

**Description about the bug**  
I haven't used the add-on in a long while and tried to enable it; The add-on can't be enabled.
- I removed it and installed latest version **3.7**: didn't work.
- I removed it and installed previous version **3.6**: didn't work.

In all cases it's the same result.

**Console log:**
```

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 386, in enable
    mod.register()
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\screencast_keys\__init__.py", line 144, in register
    register_updater(bl_info)
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\screencast_keys\__init__.py", line 78, in register_updater
    config = utils.addon_updater.AddonUpdaterConfig()
AttributeError: module 'screencast_keys.utils' has no attribute 'addon_updater'
```

**Screenshots/Files** [Optional]  
![image](https://user-images.githubusercontent.com/43890965/183265166-eb8499da-e163-4d98-bf87-0a9f75cebbee.png)

**Comment by nutti** [comment]
Please see [FAQ](https://github.com/nutti/Screencast-Keys/blob/master/docs/faq.md#failed-to-install-this-add-on).
