### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by DustyMill** [nutti/Screencast-Keys#150]
### System Information
  
* OS: Windows 10 Home
* Blender version: 3.4.1
* Add-on version: 3.9 (have tried other versions 3.4 for example)

I install the file from the ZIP folder and it installs just fine but when I go to enable it I am getting this error 

Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\giraf\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\screencast_keys\__init__.py", line 153, in register
    register_updater(bl_info)
  File "C:\Users\giraf\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\screencast_keys\__init__.py", line 84, in register_updater
    config = utils.addon_updater.AddonUpdaterConfig()
AttributeError: module 'screencast_keys.utils' has no attribute 'addon_updater'

**Comment by DustyMill** [comment]
I fixed it. Just encase anyone has this error... no idea why it happens exactly myself but deleted the Blender Foundation folder and opening Blender again fixed it
