### ISSUE TITLE
null handler

### ISSUE THREAD

**Issue by 3d-illusions** [nutti/Screencast-Keys#175]
### System Information
  
* OS: windows 10 pro
* blender 3.61
* addon version 3.91

Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed

**Comment by 3d-illusions** [comment]
then:

Traceback (most recent call last):
  File "E:\blender\shared_files_between_versions\scripts\addons\screencast_keys\ops.py", line 2120, in intialization_callback  
    bpy.types.SpaceView3D.draw_handler_remove(
ValueError: callback_remove(handler): NULL handler given, invalid or already removed
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF7C8840054
Module  : blender.exe
Thread  : 00003398
Writing: C:\Users\3diWorkstation\AppData\Local\Temp\EXHIBITION MASTER 2023.crash.txt

**Comment by 3d-illusions** [comment]
updating to 3.10 seems to have solved.
