### ISSUE TITLE
Problem to activate option

### ISSUE THREAD

**Issue by b4zz4** [nutti/Screencast-Keys#189]
### System Information
  
* OS: Linux
* Blender version: 4
* Add-on version: 3.12

### Description about the bug**

by pressing the check of "ScreenCast Keys"
 
```
Python: Traceback (most recent call last):
  File "/home/bazza/.config/blender/4.0/scripts/addons/screencast_keys/ops.py", line 1872, in modal
    if key not in cls.timers:
              ^^^^^^^^^^^^^^^^
  File "/home/bazza/.config/blender/4.0/scripts/addons/screencast_keys/ops.py", line 1085, in find_redraw_regions
    return regions
           ^^^^^^^^
  File "/home/bazza/.config/blender/4.0/scripts/addons/screencast_keys/ops.py", line 1047, in draw_area_rect
    max(y, ymin),
                  
  File "/home/bazza/.config/blender/4.0/scripts/addons/screencast_keys/ops.py", line 761, in get_origin
    rect = get_region_rect_on_v3d(
                    ^^^^^^^^^^^^^^^
  File "/home/bazza/.config/blender/4.0/scripts/addons/screencast_keys/ops.py", line 1009, in draw_area_size
    
TypeError: blf.size() takes exactly 2 arguments (3 given)

```

**Comment by nutti** [comment]
@b4zz4 

Same as #177.
Could you check this issue?
