### ISSUE TITLE
Doesn't work in Blender 4.02

### ISSUE THREAD

**Issue by stillpointx** [nutti/Screencast-Keys#190]
### System Information
  version: 4.0.2, branch: blender-v4.0-release, commit date: 2023-12-05 07:41, hash: 9be62e85b727, type: release
build date: 2023-12-05, 08:48:50
platform: 'Linux-5.15.0-91-generic-x86_64-with-glibc2.31'  Ubuntu 20.04
Screencast-Keys 3.0.0

![image](https://github.com/nutti/Screencast-Keys/assets/28985314/32ace846-7122-4f4c-857f-7bda02cd2585)

### Expected behavior

*The behavior you expect about the feature you reported.*

### Description about the bug**

Doesn't work

### Screenshots/Files [Optional]  
![image](https://github.com/nutti/Screencast-Keys/assets/28985314/1cd76907-505b-4557-b94e-a87c91197457)

```
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '2D_UNIFORM_COLOR'
rna_uiItemR: property not found: ScreenCastKeysPreferences.color
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:809
rna_uiItemR: property not found: ScreenCastKeysPreferences.color_shadow
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:810
rna_uiItemR: property not found: ScreenCastKeysPreferences.font_size
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:811
rna_uiItemR: property not found: ScreenCastKeysPreferences.display_time
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:812
rna_uiItemR: property not found: ScreenCastKeysPreferences.origin
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:816
rna_uiItemR: property not found: ScreenCastKeysPreferences.offset
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:818
rna_uiItemR: property not found: ScreenCastKeysPreferences.show_last_operator
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:821
rna_uiItemR: property not found: ScreenCastKeysPreferences.color
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:809
rna_uiItemR: property not found: ScreenCastKeysPreferences.color_shadow
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:810
rna_uiItemR: property not found: ScreenCastKeysPreferences.font_size
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:811
rna_uiItemR: property not found: ScreenCastKeysPreferences.display_time
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:812
rna_uiItemR: property not found: ScreenCastKeysPreferences.origin
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:816
rna_uiItemR: property not found: ScreenCastKeysPreferences.offset
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:818
rna_uiItemR: property not found: ScreenCastKeysPreferences.show_last_operator
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:821
rna_uiItemR: property not found: ScreenCastKeysPreferences.color
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:809
rna_uiItemR: property not found: ScreenCastKeysPreferences.color_shadow
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:810
rna_uiItemR: property not found: ScreenCastKeysPreferences.font_size
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:811
rna_uiItemR: property not found: ScreenCastKeysPreferences.display_time
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:812
rna_uiItemR: property not found: ScreenCastKeysPreferences.origin
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:816
rna_uiItemR: property not found: ScreenCastKeysPreferences.offset
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:818
rna_uiItemR: property not found: ScreenCastKeysPreferences.show_last_operator
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:821
rna_uiItemR: property not found: ScreenCastKeysPreferences.color
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:809
rna_uiItemR: property not found: ScreenCastKeysPreferences.color_shadow
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:810
rna_uiItemR: property not found: ScreenCastKeysPreferences.font_size
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:811
rna_uiItemR: property not found: ScreenCastKeysPreferences.display_time
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:812
rna_uiItemR: property not found: ScreenCastKeysPreferences.origin
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:816
rna_uiItemR: property not found: ScreenCastKeysPreferences.offset
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:818
rna_uiItemR: property not found: ScreenCastKeysPreferences.show_last_operator
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:821
rna_uiItemR: property not found: ScreenCastKeysPreferences.color
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:809
rna_uiItemR: property not found: ScreenCastKeysPreferences.color_shadow
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:810
rna_uiItemR: property not found: ScreenCastKeysPreferences.font_size
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:811
rna_uiItemR: property not found: ScreenCastKeysPreferences.display_time
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:812
rna_uiItemR: property not found: ScreenCastKeysPreferences.origin
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:816
rna_uiItemR: property not found: ScreenCastKeysPreferences.offset
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:818
rna_uiItemR: property not found: ScreenCastKeysPreferences.show_last_operator
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:821
rna_uiItemR: property not found: ScreenCastKeysPreferences.color
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:809
rna_uiItemR: property not found: ScreenCastKeysPreferences.color_shadow
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:810
rna_uiItemR: property not found: ScreenCastKeysPreferences.font_size
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:811
rna_uiItemR: property not found: ScreenCastKeysPreferences.display_time
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:812
rna_uiItemR: property not found: ScreenCastKeysPreferences.origin
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:816
rna_uiItemR: property not found: ScreenCastKeysPreferences.offset
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:818
rna_uiItemR: property not found: ScreenCastKeysPreferences.show_last_operator
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:821
rna_uiItemR: property not found: ScreenCastKeysPreferences.color
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:809
rna_uiItemR: property not found: ScreenCastKeysPreferences.color_shadow
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:810
rna_uiItemR: property not found: ScreenCastKeysPreferences.font_size
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:811
rna_uiItemR: property not found: ScreenCastKeysPreferences.display_time
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:812
rna_uiItemR: property not found: ScreenCastKeysPreferences.origin
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:816
rna_uiItemR: property not found: ScreenCastKeysPreferences.offset
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:818
rna_uiItemR: property not found: ScreenCastKeysPreferences.show_last_operator
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:821
rna_uiItemR: property not found: ScreenCastKeysPreferences.color
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:809
rna_uiItemR: property not found: ScreenCastKeysPreferences.color_shadow
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:810
rna_uiItemR: property not found: ScreenCastKeysPreferences.font_size
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:811
rna_uiItemR: property not found: ScreenCastKeysPreferences.display_time
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:812
rna_uiItemR: property not found: ScreenCastKeysPreferences.origin
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:816
rna_uiItemR: property not found: ScreenCastKeysPreferences.offset
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:818
rna_uiItemR: property not found: ScreenCastKeysPreferences.show_last_operator
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:821
rna_uiItemR: property not found: ScreenCastKeysPreferences.color
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:809
rna_uiItemR: property not found: ScreenCastKeysPreferences.color_shadow
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:810
rna_uiItemR: property not found: ScreenCastKeysPreferences.font_size
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:811
rna_uiItemR: property not found: ScreenCastKeysPreferences.display_time
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:812
rna_uiItemR: property not found: ScreenCastKeysPreferences.origin
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:816
rna_uiItemR: property not found: ScreenCastKeysPreferences.offset
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:818
rna_uiItemR: property not found: ScreenCastKeysPreferences.show_last_operator
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:821
Traceback (most recent call last):
  File "/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py", line 639, in modal
    regions = self.find_redraw_regions(context)
  File "/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py", line 372, in find_redraw_regions
    rect = cls.calc_draw_rectangle(context)
  File "/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py", line 305, in calc_draw_rectangle
    blf.size(font_id, font_size, dpi)
TypeError: blf.size() takes exactly 2 arguments (3 given)
Error: Python: Traceback (most recent call last):
  File "/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py", line 639, in modal
    regions = self.find_redraw_regions(context)
  File "/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py", line 372, in find_redraw_regions
    rect = cls.calc_draw_rectangle(context)
  File "/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py", line 305, in calc_draw_rectangle
    blf.size(font_id, font_size, dpi)
TypeError: blf.size() takes exactly 2 arguments (3 given)

rna_uiItemR: property not found: ScreenCastKeysPreferences.color
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:809
rna_uiItemR: property not found: ScreenCastKeysPreferences.color_shadow
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:810
rna_uiItemR: property not found: ScreenCastKeysPreferences.font_size
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:811
rna_uiItemR: property not found: ScreenCastKeysPreferences.display_time
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:812
rna_uiItemR: property not found: ScreenCastKeysPreferences.origin
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:816
rna_uiItemR: property not found: ScreenCastKeysPreferences.offset
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:818
rna_uiItemR: property not found: ScreenCastKeysPreferences.show_last_operator
/home/rt/.config/blender/4.0/scripts/addons/screencastkeys/ops.py:821

```

**Comment by stillpointx** [comment]
Update to version 3.12 fixed crash
