### ISSUE TITLE
Error when trying to install into Blender 4.0

### ISSUE THREAD

**Issue by fole2150** [nutti/Screencast-Keys#197]
### System Information
  Using blender 4.0 and Screencast Keys version 3.13
* OS: [e.g. Windows]
* Blender version: [4.0]
* Add-on version: [3.13]

### Expected behavior
When I click on the add-on in blender's add-ons I get this error. 

*The behavior you expect about the feature you reported.*

### Description about the bug**

Error says the following: "Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 401, in enable
    mod.register()
  File "C:\Users\Lady Death\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\screencast_keys\__init__.py", line 156, in register
    if not common.is_console_mode():
AttributeError: module 'screencast_keys.common' has no attribute 'is_console_mode'
"

*The description about the bug.*

### Screenshots/Files [Optional]  

*It is good to solve the bug if you attach the screenshots or .blend file.*

**Comment by fole2150** [comment]
Required restarting blender, now I don't get the error. Sorry!
