### ISSUE TITLE
i still can´t use it in blender 4.0

### ISSUE THREAD

**Issue by sahk75** [nutti/Screencast-Keys#199]
### System Information
  
* OS: [e.g. Windows]
* Blender version: [e.g. 4.0]
* Add-on version: [e.g. 3.12]

### Expected behavior

*The behavior you expect about the feature you reported.*

### Description about the bug**

*The description about the bug.*

### Screenshots/Files [Optional]  
Python: Traceback (most recent call last):
  File "C:\Users\elune\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\screencast_keys\ops.py", line 1708, in modal
    reset = True
  File "C:\Users\elune\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\screencast_keys\ops.py", line 1021, in find_redraw_regions
    if not window:
  File "C:\Users\elune\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\screencast_keys\ops.py", line 984, in calc_draw_area_rect
    # Calculate width/height of draw area.
  File "C:\Users\elune\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\screencast_keys\ops.py", line 727, in get_origin
    window = None
  File "C:\Users\elune\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\screencast_keys\ops.py", line 949, in calc_draw_area_size
    
TypeError: blf.size() takes exactly 2 arguments (3 given)

https://prnt.sc/DaZoKob230Qm

*It is good to solve the bug if you attach the screenshots or .blend file.*

**Comment by nutti** [comment]
@sahk75 

Same as #177 .
But this issue has already fixed.

I think the add-on update is not reflected to Blender.
Restart Blender, or install the unstable version may fix this issue.
Could you try it?
