### ISSUE TITLE
Error and Screencast Keys stop being displayed when using measurement tool

### ISSUE THREAD

**Issue by GesaP** [nutti/Screencast-Keys#36]
* OS: [ Windows]
* Blender version: [2.9]
* Add-on version: [3.0.0]

After some actions the Screencast Keys stop being displayed.
Confirmed is trying to use the measurement tool, I have seen it in at least one other occasion (though I am not sure which action did this there)

Error says:
```
Traceback (most recent call last):
  File "C:\Users\MyName\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\screencastkeys\ops.py", line 587, in modal
    event_type = EventType[event.type]
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\lib\enum.py", line 352, in __getitem__
    return cls._member_map_[name]
KeyError: ''

location: <unknown location>:-1
```

Blender throws this error and the screencast keys stop being displayed. They start being displayed again after un-ticking and ticking the activation box once.

**Comment by GesaP** [comment]
Apparently fixed in 3.3. Thanks!
