### ISSUE TITLE
Error when importing to 2.76

### ISSUE THREAD

**Issue by dualhammers** [nutti/Screencast-Keys#43]
```
Traceback (most recent call last):
  File "../Resources/2.76/scripts/modules/addon_utils.py", line 324, in enable
    mod = __import__(module_name)
  File "/Users/vigneur/Library/Application Support/Blender/2.76/scripts/addons/screencast_keys/__init__.py", line 48, in <module>
    from . import utils
  File "/Users/vigneur/Library/Application Support/Blender/2.76/scripts/addons/screencast_keys/utils/__init__.py", line 29, in <module>
    from . import addon_updater
ImportError: cannot import name 'addon_updater'


```

I tried importing the .zip file I grabbed from the release page. Version 3.4

**Comment by nutti** [comment]
@dualhammers 

Screencast Keys does not support Blender 2.76.
Blender 2.79 is the last Blender version which Screencast Keys supports.
Could you try Blender 2.79 instead?

**Comment by nutti** [comment]
I will close this issue for now.
