### ISSUE TITLE
Screencast-Keys v3.4 can Not work in Blender v2.93!

### ISSUE THREAD

**Issue by zgkony** [nutti/Screencast-Keys#47]
Hi Nutti,

Screencast-Keys v3.4 can Not work in Blender v2.93! In win10_X64,your Kit can Not work,please fixed it in your free time,thanks!!!

**Comment by nutti** [comment]
We could not handle this issue without any information.
I think this is related to the #45, so I will close this issue.

**Comment by zgkony** [comment]
> Hi Nutti,
> 
> Screencast-Keys v3.4 can Not work in Blender v2.93! In win10_X64,your Kit can Not work,please fixed it in your free time,thanks!!!

**Comment by nutti** [comment]
@zgkony 

Did you restart Blender after you installed the below add-on?
https://github.com/nutti/Screencast-Keys/archive/issue_45.zip

I encountered this kind of the error when I try to enable add-on without restarting Blender.

**Comment by Irmitya** [comment]
@nutti that's not confirmed to be their problem. 
The issue I'm reading from their second post, is the addon was disabled/re-enabled/etc, without the addon being unregistered correctly first. 

#45 is only applicable if the Blender version they're using specifies the thing mentioned in #45, with `bpy_prop_deferred`

**Comment by zgkony** [comment]
@nutti I had restarted Blender,but your kit still Not work.
Errors show:

bpy.data.window_managers["WinMan"].addon_search = "scr"
Traceback (most recent call last):
  File "K:\3D_Software\Blender\blender-2.93.0-37e6a1995ac7-windows64\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\GZ3D\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\screencast_keys\__init__.py", line 49, in <module>
    from . import preferences
  File "C:\Users\GZ3D\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\screencast_keys\preferences.py", line 52, in <module>
    class SK_OT_UpdateAddon(bpy.types.Operator):
  File "C:\Users\GZ3D\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\screencast_keys\utils\compatibility.py", line 51, in make_annotations
    props = {k: v for k, v in cls.__dict__.items() if isinstance(v, bpy.props._PropertyDeferred)}
  File "C:\Users\GZ3D\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\screencast_keys\utils\compatibility.py", line 51, in <dictcomp>
    props = {k: v for k, v in cls.__dict__.items() if isinstance(v, bpy.props._PropertyDeferred)}
AttributeError: module 'bpy.props' has no attribute '_PropertyDeferred'

**Comment by nutti** [comment]
@zgkony 

This is the same issue described in #45.
I have already merged the patch to solve this issue to the master branch.

**Comment by zgkony** [comment]
@nutti 

I had updated my Blender v2.93(February 25 pack),and use your new kit, it work well, Thank you very much!!!
