### ISSUE TITLE
Doesnt function on blender 2.93.1LTS

### ISSUE THREAD

**Issue by Murkur** [nutti/Screencast-Keys#61]
**System Information**

* OS: Windows 10 PRO

* Blender version: 
  [2.93.1LTS]
* Add-on version: 
  [3.5.0]

**Expected behavior**  
Enabling addon

**Description about the bug**  
Plugin fails to enable 

**Screenshots/Files** 
![image](https://user-images.githubusercontent.com/20288698/123515424-50c41200-d665-11eb-81ce-b8800afcd617.png)

**Additional comments** 

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 386, in enable
    mod.register()
  File "C:\Users\Myrkur\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\screencast_keys\__init__.py", line 118, in register
    bpy.utils.register_class(preferences.DisplayEventTextAliasProperties)
ValueError: register_class(...): already registered as a subclass 'DisplayEventTextAliasProperties'

```

**Comment by Murkur** [comment]
Reinstalled blender and for some reason that functioned think maybe blender was still seeing the last version as being registered and didn't update till settings got reset by reinstall
