### ISSUE TITLE
Will not enable on Blender 2.93.0

### ISSUE THREAD

**Issue by jlerossignol** [nutti/Screencast-Keys#65]
**System Information**
  
* OS: [Windows]
* Blender version: 2.93.0
* Add-on version: 3.5.0

**Expected behavior**  
* When you tick the enable box in the add-ons it will enable, but it generates an error message, see below.

**Description about the bug**  
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 386, in enable
    mod.register()
  File "C:\Users\lerossignol.jamie\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\screencast_keys\__init__.py", line 116, in register
    register_updater(bl_info)
  File "C:\Users\lerossignol.jamie\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\screencast_keys\__init__.py", line 76, in register_updater
    config = utils.addon_updater.AddonUpdaterConfig()
AttributeError: module 'screencast_keys.utils' has no attribute 'addon_updater'

**Screenshots/Files** [Optional]  
*It is good to solve the bug if you attach the screenshots or .blend file.*
![image](https://user-images.githubusercontent.com/6948075/126723618-e6d3f42a-f77e-4d96-8c22-8b3cdbdfcd48.png)

**Additional comments** [Optional]

**Comment by nutti** [comment]
Same as #64

**Comment by Kureii** [comment]
Problem have easy solution. You have install addon in program files and in appdata, just delete it from one directory. I recommended delete it from program files.
The second type od solution is: click on remove button, restart blender and install addon again :)
This also happens with other add-ons

**Comment by jlerossignol** [comment]
Yes. I did that, three times. Twice from Preferences > Add-ons , and the
third from the folder structure
