### ISSUE TITLE
Not Working With Blender 3.0.0

### ISSUE THREAD

**Issue by naruaika** [nutti/Screencast-Keys#89]
**System Information**
  
* OS: Windows 11
* Blender version: 3.0.0
* Add-on version: 3.6

**Expected behavior**  
All the options are displayed properly as shown in the demo video:
![image](https://user-images.githubusercontent.com/26834955/147997353-e7e889cb-a52f-4174-b3d9-9a2000e430ff.png)

**Description about the bug**  
Only get a button instead:
![image](https://user-images.githubusercontent.com/26834955/147997433-e8bf25d1-790a-4cf3-b986-d2e4d426987f.png)
These error appeared after opening the Screencast Keys menu in the Properties Panel:
```bash
rna_uiItemR: property not found: ScreenCastKeysPreferences.color

C:\Users\naruaika\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\screencastkeys\ops.py:809
rna_uiItemR: property not found: ScreenCastKeysPreferences.color_shadow

C:\Users\naruaika\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\screencastkeys\ops.py:810
rna_uiItemR: property not found: ScreenCastKeysPreferences.font_size

C:\Users\naruaika\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\screencastkeys\ops.py:811
rna_uiItemR: property not found: ScreenCastKeysPreferences.display_time

C:\Users\naruaika\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\screencastkeys\ops.py:812
rna_uiItemR: property not found: ScreenCastKeysPreferences.origin

C:\Users\naruaika\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\screencastkeys\ops.py:816
rna_uiItemR: property not found: ScreenCastKeysPreferences.offset

C:\Users\naruaika\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\screencastkeys\ops.py:818
rna_uiItemR: property not found: ScreenCastKeysPreferences.show_last_operator

C:\Users\naruaika\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\screencastkeys\ops.py:821
```
And these errors occured after enabling the screencast:
```bash
Python: Traceback (most recent call last):
  File "C:\Users\naruaika\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\screencastkeys\ops.py", line 639, in modal
    regions = self.find_redraw_regions(context)
  File "C:\Users\naruaika\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\screencastkeys\ops.py", line 372, in find_redraw_regions
    rect = cls.calc_draw_rectangle(context)
  File "C:\Users\naruaika\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\screencastkeys\ops.py", line 305, in calc_draw_rectangle
    blf.size(font_id, font_size, dpi)
TypeError: an integer is required (got type _PropertyDeferred)

location: <unknown location>:-1
```
Also, the Preferences just blank:
![image](https://user-images.githubusercontent.com/26834955/147997930-b412e6d4-0f9c-4c9b-b6a9-e2ce4e24f93a.png)
with this error:
```bash
rna_uiItemR: property not found: ScreenCastKeysPreferences.category

C:\Users\naruaika\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\screencastkeys\preferences.py:149
```

**Comment by naruaika** [comment]
Pardon me! The unstable version of the add-on worked perfectly. Let me close this issue.
