### ISSUE TITLE
Screencast Keys not working on Blender 3.1

### ISSUE THREAD

**Issue by 3dcinetv** [nutti/Screencast-Keys#99]
**System Information**
  
* OS: [e.g. Windows]
* Blender version: 3.2
* Add-on version: 3.6

**Expected behavior**  
Addon would install normally, but it doesn't.

**Description about the bug**  
The addon doesn't install.

**Screenshots/Files** [Optional]  
[Screenshot>>](https://imgur.com/hmqoo82)

**Additional comments** [Optional]
Traceback (most recent call last):
  File "E:\Program Files\Blender-3.2\3.2\scripts\modules\addon_utils.py", line 371, in enable
    mod.register()
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\screencast_keys\__init__.py", line 154, in register
    utils.bl_class_registry.BlClassRegistry.register()
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\screencast_keys\utils\bl_class_registry.py", line 63, in register
    bpy.utils.register_class(class_["class"])
ValueError: bpy_struct "SK_Preferences" registration error: 'font_size' IntProperty could not register (see previous error)

**Comment by nutti** [comment]
This relates to #73 .
Try to use the unstable version for now.
https://github.com/nutti/Screencast-Keys/blob/master/docs/installation.md#manual-install

**Comment by nutti** [comment]
@3dcinetv 

Is there any update?
If there is no response, I will close this issue in a few day.

**Comment by 3dcinetv** [comment]
I am on Blender 3.2, thank you for the follow up.
Yes, manual install of this "unstable version" works in Blender 3.2 normally.

**Comment by nutti** [comment]
Glad to hear that.
Close this issue now.
